# utils.cmake
function(get_vs_group_name FILE_PATH OUTPUT)
    file(RELATIVE_PATH REL_PATH "${CMAKE_CURRENT_SOURCE_DIR}" "${FILE_PATH}")

    if(REL_PATH MATCHES "^src/(.*)")
        set(REL_PATH "${CMAKE_MATCH_1}")
    elseif(REL_PATH MATCHES "^include/bismuth/(.*)")
        set(REL_PATH "${CMAKE_MATCH_1}")
    endif()

    get_filename_component(DIR_PATH "${REL_PATH}" PATH)
    if(DIR_PATH STREQUAL "")
        set(${OUTPUT} "" PARENT_SCOPE)
    else()
        string(REPLACE "\\" "/" DIR_PATH "${DIR_PATH}")
        string(REPLACE "/" ";" PATH_PARTS "${DIR_PATH}")
        set(CAPITALIZED_PATH "")

        foreach(PART ${PATH_PARTS})
            string(TOLOWER "${PART}" PART_LOWER)
            if(PART_LOWER STREQUAL "sdl")
                set(PART "SDL")
            else()
                string(SUBSTRING "${PART}" 0 1 FIRST_CHAR)
                string(SUBSTRING "${PART}" 1 -1 REST_CHARS)
                string(TOUPPER "${FIRST_CHAR}" FIRST_CHAR)
                set(PART "${FIRST_CHAR}${REST_CHARS}")
            endif()
            list(APPEND CAPITALIZED_PATH "${PART}")
        endforeach()

        string(REPLACE ";" "/" CAPITALIZED_PATH "${CAPITALIZED_PATH}")
        set(${OUTPUT} "${CAPITALIZED_PATH}" PARENT_SCOPE)
    endif()
endfunction()
